version: "2"
services:
  sprinklr-application:
    image: yros/sprinklr-application:latest
    container_name: sprinklr_application
    networks:
     - backend
    ports:
     - "8080"
    volumes:
     - ./.:/app
    environment:
     - VIRTUAL_HOST=sprinklr-application
     - VIRTUAL_PORT=8080
    links:
     - nginx-proxy
    command: bash -c "npm install && npm start"
 
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
     - "80:80"
    environment:
      - DEFAULT_HOST=sprinklr-application
    networks:
     - backend
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
    backend:
     driver: bridge

